### ISSUE TITLE
Problems around the provisioning form

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-redfish#105]
I noticed that the provisioning form is broken for Redfish Physical Servers. Probably for other servers as well, because the one initiated from the GTL can be used for any kind of physical server which is probably a bug.

![Screenshot from 2020-05-04 18-35-10](https://user-images.githubusercontent.com/649130/80990867-63630280-8e37-11ea-9957-867c8ad360e8.png)

The problem is that the *Customization Template* dropdown never comes active and so the user can not submit the form at all:
![Screenshot from 2020-05-04 18-37-30](https://user-images.githubusercontent.com/649130/80990331-74f7da80-8e36-11ea-9a69-4c0ae9940d4b.png)

I'm working on DDF conversions in the area and I thought the fix could be just to rewrite this into DDF, but unfortunately we don't support dynamic loading of dropdowns based on a previously selected dropdown value yet. However, according to @hyperkid123 this functionality is implemented in DDFv2.

My goal is to get rid of the FinalForm components so we can get rid of the final-form package dependency from react-ui-components which would allow us to update to DDFv2. But here I am blocked by a missing feature from DDFv1 which is available in DDFv2.

So is it okay if I temporarily make this component unavailable until we update everything around it to DDFv2? Then I could implement the form in DDF and also fix the problem described above.

cc @himdel

**Comment by matejart** [comment]
Just to check, is the `test` image assigned to (writing off the top of my head) an image type? And are there customization templates associated with that image type?

**Comment by skateman** [comment]
@matejart yes :wink: I know how to quick-fix this, it is not a problem, there's just an extra `else` that should be removed. But my problem is how to go further, there's some behavior implemented which I can't implement using DDFv1 and to update to DDFv2, I have to get rid of the current implementation that depends on final-form.

**Comment by skateman** [comment]
Okay, after a few hours of hacking, I was able to work around the problem in the old DDF and there's a  fixed version. Closing this issue, we don't need to break anything :pray:

**Comment by matejart** [comment]
@skateman and it shows how much I know while venturing ahead to ask basic questions anyway. ;)
