### ISSUE TITLE
Provider injects toolbar buttons to entities of other providers

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-redfish#111]
The `PhysicalServersCenter` toolbar override displays the `Provision Selected Physical Servers` and `Update Firmware of Physical Servers` on the `Physical Servers` screen. This allows the user to invoke these dialogs on entities coming from any provider. This can even happen when the user doesn't have a redfish provider added.

![Screenshot from 2020-05-21 14-25-17](https://user-images.githubusercontent.com/649130/82558871-ea6de580-9b6e-11ea-9fec-352877d20eca.png)

A quick fix would be to not allow this toolbar override from the show_list screen, only from the summary screen of a correct entity.

cc @himdel 
@miq-bot add_label bug

**Comment by himdel** [comment]
It's a general UI problem - list screens can not use condtions based on `@record`, including type.

That by itself is not an issue, as long as the provider code expects, and is able to gracefully handle instances of incompatible types.

If the toolbar blows up when given a Lenovo Physical server, that's a bug.
If it simply notifies about specific servers not being compatible and excludes them, that's OK :).

**Comment by skateman** [comment]
Well, you have the access to the button even if you don't have a redfish provider. This part we could fix easily by hiding the button if there's no provider available. But I'd rather not have provider-specific things on show_list screens as long as we are not able to set onwhen based on a more complex condition than comparing numbers.

It just feels wrong to me that from a provider you have to count with other providers...

**Comment by skateman** [comment]
After the meeting, we agreed that getting rid of the buttons from the GTLs would significantly degrade the usability. So instead I'm changing the buttons to contain the provider's name in the button text and make the visibility depend on the existence of a given provider in the inventory.

**Comment by Fryguy** [comment]
How do we do it in Cloud or Infra?  I'm surprised that we have this at all, since I'd expect the provider to use the support feature capability and core then reads that.

**Comment by skateman** [comment]
@Fryguy these are provider-defined "pluggable" buttons, kinda different from what we do in cloud or infra.

**Comment by Fryguy** [comment]
Yeah I'm saying they shouldn't be in this case... I'd expect all physical providers to offer these features as part of the common interface and use the supports feature mechanism to say whether or not they actually do.

If a provider brings actual provider-specific things they should not infect the main menus, but instead create their own menu on the summary page (or at least that was the expected design). 

@agrare thoughts?

**Comment by skateman** [comment]
Well, they don't really implement it in all providers, just this single one. I also would like to have a button tied to a summary screen, but these two features are capable of handling multiple entities at the same time. Thinking about a real-world use case of a firmware update on a lot of physical servers...

**Comment by agrare** [comment]
@Fryguy yeah I'm not seein why these wouldn't be in core and only enabled for providers which support the feature.  This might have been a good way to bring new features before they can land in ui-classi but it prevents other providers who might want to implement the feature from doing so.

If another physical infra provider came along and wanted to implement firmware update they'd have to copy the button code in their repo.
