### ISSUE TITLE
Factory definition causing warnings elsewhere

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-redfish#15]
I am seeing this warning when running tests in ManageIQ

```
/Users/jfrey/.gem/ruby/2.4.2/bundler/gems/manageiq-providers-redfish-7e52b751b92a/spec/factories/physical_server.rb:3: warning: toplevel constant PhysicalServer referenced by ManageIQ::Providers::Redfish::PhysicalInfraManager::PhysicalServer
```

I am guessing that somewhere the `ManageIQ::Providers::Redfish::PhysicalInfraManager::PhysicalServer` is not actually defined, but is being referenced.

cc @tadeboro

**Comment by tadeboro** [comment]
I never noticed this warning, since it only manifests itself when running the test suite from the core repo. If I run tests from the Redfish provider repo, no warning is there.

Anyhow, I hopefully managed to get rid of this warning by forcing FactoryGirl to load PhysicalServer class lazily.
