### ISSUE TITLE
Security Protocol not populated for existing Redfish provider

### ISSUE THREAD

**Issue by matejart** [ManageIQ/manageiq-providers-redfish#18]
I created a Redfish physical infrastructure provider, in the process of which I selected in _Endpoints_ section the _Security Protocol_ value (e.g., _No-SSL_). 

Later, when I opened this infrastructure provider and used _Configuration_ > _Edit this Infrastructure Provider_, all fields except for _Endpoints_ > _Security Protocol_ were pre-populated. This field has to be populated by the previously stored value.

**Comment by tadeboro** [comment]
This issue should be resolved by modifying the ManageIQ UI.

@miq-bot move_issue manageiq-ui-classic
