### ISSUE TITLE
HPE Proliant Gen9 redfish provider gives Authentication status as "invalid"

### ISSUE THREAD

**Issue by SLoeuillet** [ManageIQ/manageiq-providers-redfish#55]
In CloudForms 4.7.1 / 5.10.1.2, I've got several Gen8 and Gen9 servers (ILO4) for which data is gathered but "Authentication status" is "invalid"

If it was invalid, it couldn't have gathered model number, ram, cpu, ... in the first place.

Don't know if it is related but when calling the redfish_client logout method, I've got an exception 

/opt/rh/cfme-gemset/gems/redfish_client-0.4.1/lib/redfish_client/resource.rb:182:in `get_path': RedfishClient::Resource::NoODataId (RedfishClient::Resource::NoODataId)
        from /opt/rh/cfme-gemset/gems/redfish_client-0.4.1/lib/redfish_client/resource.rb:167:in `delete'
        from /opt/rh/cfme-gemset/gems/redfish_client-0.4.1/lib/redfish_client/root.rb:102:in `session_logout'
        from /opt/rh/cfme-gemset/gems/redfish_client-0.4.1/lib/redfish_client/root.rb:45:in `logout'
        from ./test_redfish.rb:12:in `<main>'

[root@mpdrhcfm01v ~]# cat test_redfish.rb
require "redfish_client"

root = RedfishClient.new("https://mpdcsdbo01a-lc.oad.exch.int",
                         prefix: "/redfish/v1",
                         verify: false)
puts root
root.login("ZZZZ", "XXXXXXXXX.")

puts root.Chassis
puts root.Systems
puts root.Managers
root.logout

**Comment by tadeboro** [comment]
This suggests that when new session is created, no `@odata.id` is returned in the resource. Add `puts` in front of the `root.login()` call to dump session data to the output and look for `@odata.id` field. If this field is missing, ILO4 is not speaking the Redfish API properly.

**Comment by SLoeuillet** [comment]
Interresting 

puts root (at start) prints what looks like valid RedFish output (so, without authent/anonymously)

but trying to login fails, it shows the following

{
  "error": {
    "code": "iLO.0.10.ExtendedInfo",
    "message": "See @Message.ExtendedInfo for more information.",
    "@Message.ExtendedInfo": [
      {
        "MessageId": "Base.1.0.Created"
      }
    ]
  }
}

**Comment by SLoeuillet** [comment]
oh, that's on HPE Gen10, so ILO5 1.40 in that case
Retrying in ILO4 2.61 on HPE Gen9 

It makes this "entirely different" message 

{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "MessageId": "Base.0.10.Created"
      }
    ],
    "code": "iLO.0.10.ExtendedInfo",
    "message": "See @Message.ExtendedInfo for more information."
  }
}

**Comment by tadeboro** [comment]
This is not an error, this is how success is reported back in Redfish. Not sure why the decided to reuse error report json document structure for success messages, but there is not much we can do here.

But this is just a side-problem. The main problem here is that ILO should return session representation back when user logs in, not a error/success message. [Session management part](http://redfish.dmtf.org/schemas/DSP0266_1.6.1.html#session-management) of the standard clearly defines this.

**Comment by SLoeuillet** [comment]
OK, so login works but it make session_logout fail and report and error as session_logout wants to report the ODataId that should have been given at login, right ?

**Comment by tadeboro** [comment]
Exactly. When the client logs in, it stores the session in order to be able to terminate it on logout. But because ILO returns success message instead of session document, session deletion fails when it tries to send `DELETE` request to the path listed in `@odata.id`.

**Comment by SLoeuillet** [comment]
Looks like trying a curl works (not ruby client)

curl --user admin:XXXX --request GET --silent --insecure --header "OData-Version: 4.0" https://mpdcsdbo01a-lc.oad.exch.int/redfish/v1/SessionService/Sessions/

{"@odata.context":"/redfish/v1/$metadata#SessionCollection.SessionCollection","@odata.etag":"W/\"70781EF9\"","@odata.id":"/redfish/v1/SessionService/Sessions/","@odata.type":"#SessionCollection.SessionCollection","Description":"Manager User Sessions","Name":"Sessions","Oem":{"Hpe":{"@odata.context":"/redfish/v1/$metadata#HpeiLOSessionsSummary.HpeiLOSessionsSummary","@odata.type":"#HpeiLOSessionsSummary.v2_0_0.HpeiLOSessionsSummary","Links":{"MySession":{"@odata.id":"/redfish/v1/SessionService/Sessions/admin000000005ca1d5e2e9f3034e/"}}}},"Members":[{"@odata.id":"/redfish/v1/SessionService/Sessions/admin000000005ca1d5e2e9f3034e/"}],"Members@odata.count":1}

**Comment by SLoeuillet** [comment]
Invalid JSON ? "@odata.etag":"W/"70781EF9""

**Comment by SLoeuillet** [comment]
I'm going to open bug reports with HPE but have you got a way to make the JSON parser more "relax" ?

**Comment by tadeboro** [comment]
> Looks like trying a curl works (not ruby client)
> 
> curl --user admin:XXXX --request GET --silent --insecure --header "OData-Version: 4.0" https://mpdcsdbo01a-lc.oad.exch.int/redfish/v1/SessionService/Sessions/

To create new session, we must send `POST` request to the Redfish API. Using curl, this would be done like so:

    $ curl -vk -X POST \
        -H "Odata-Version: 4.0" \
        -H "Content-Type: application/json" \
        -d '{"UserName": "tadej", "Password": "test"}' \
        https://localhost:8000/redfish/v1/SessionService/Sessions

And the returned data should look something like this:

    {
      "@odata.id":"/redfish/v1/SessionService/Sessions/d12de4d0-0a39-4334-a079-af1c9cfd2c8a",
      "Id":"d12de4d0-0a39-4334-a079-af1c9cfd2c8a",
      "Name":"d12de4d0-0a39-4334-a079-af1c9cfd2c8a",
      "@odata.type":"#Session.v1_1_0.Session",
      "UserName":"tadej",
      "Password":null
    }

ILO returns error message instead here and makes client to fail on session deletion.

**Comment by tadeboro** [comment]
> Invalid JSON ? "@odata.etag":"W/"70781EF9""

I guess someone forgot to escape double quotes in value, which makes this invalid.

**Comment by tadeboro** [comment]
> I'm going to open bug reports with HPE but have you got a way to make the JSON parser more "relax" ?

There is no way to reliably fix this sort of issues, because once we hit the error, there is no reliable way to detect where it is safe to start parsing data again.

To be completely honest, I really do not feel like fixing this just because a single vendor cannot produce a valid json. We have tested this against Lenovo, DELL, SuperMicro and even some HPE Cloudline servers and all of them managed to return valid json back.

**Comment by tadeboro** [comment]
I am closing this issue since it has nothing to do with the ManageIQ provider. If you have anything else to add, open new issue in the [redfish-client-ruby](https://github.com/xlab-si/redfish-client-ruby) repo.

@miq-bot close_issue

**Comment by anupamaloke** [comment]
@tadeboro, somehow the [redfish-client-ruby ](https://github.com/xlab-si/redfish-client-ruby) link is broken. Do you know where I can access this repository?

**Comment by chessbyte** [comment]
indeed, the "Homepage" link of https://rubygems.org/gems/redfish_client/versions/0.4.1 is broken

**Comment by Fryguy** [comment]
cc @agrare ^^
