### ISSUE TITLE
run spec always error: like uninitialized constant problem

### ISSUE THREAD

**Issue by sckhg1367** [ManageIQ/manageiq-providers-redfish#66]
root@c860fa06277a:/manageiq-providers-redfish# rspec

An error occurred while loading ./spec/manageiq/app/models/customization_spec.rb.
Failure/Error:
  class CustomizationSpec < ApplicationRecord
    belongs_to :ext_management_system, :foreign_key => "ems_id"

    serialize :spec

    def is_sysprep_spec?
      self[:spec].fetch_path(['identity', 'value']).nil?
    end

    def is_sysprep_file?

NameError:
  uninitialized constant ApplicationRecord
# ./spec/manageiq/app/models/customization_spec.rb:1:in `<top (required)>'

**Comment by tadeboro** [comment]
This error has nothing to do with Redfish provider. Make sure you have prepared a development environment as instructed in the [developer setup documentation][dev]. Then you can read the documentation on [developing individual providers][prov] where you can find details about running a test suite.

[dev]: https://github.com/ManageIQ/guides/blob/master/developer_setup.md
[prov]: https://github.com/ManageIQ/guides/blob/master/developer_setup/plugins.md

@miq-bot close_issue

**Comment by sckhg1367** [comment]
thank you very much
