### ISSUE TITLE
physical_server_details and physical_chassis_details table

### ISSUE THREAD

**Issue by sckhg1367** [ManageIQ/manageiq-providers-redfish#75]
hi guys,
i watched code have physical_server_details and physical_chassis_details tables,
physical_server and  physical_chassis information also show in web ui.
but can not find these tables in postgres sql.

do you know  which table replace these tables.

**Comment by tadeboro** [comment]
Dear Jimmy.

Please stop abusing the issue tracker. The primary purpose of an issue is to describe a bug, start a discussion about missing features, etc. And your report fits into none of the above.

If you have a question about development or having troubles while using ManageIQ, [Gitter][] or [ManageIQ talk][talk]. You will get your answers there faster without making developers who work on parts f ManageIQ angry at you.

   [Gitter]: https://gitter.im/ManageIQ/manageiq (ManageIQ Gitter)
   [talk]: http://talk.manageiq.org/ (ManageIQ Discourse)

And the last piece of advice: if you are serious about developing a provider for ManageIQ, you will need to read a book or two about Ruby on Rails. Then the questions like this one will no longer be necessary.

So please, start acting responsibly and do your homework before asking questions in inappropriate places.

Cheers, Tadej.

@miq-bot close_issue

**Comment by sckhg1367** [comment]
Sorry.
