### ISSUE TITLE
Provisioning requests from provider's server list do not work

### ISSUE THREAD

**Issue by matejart** [ManageIQ/manageiq-providers-redfish#79]
It is not possible to request a successful physical server provisioning from a selected *All Physical Servers* list. The request always contains just 1 server with a fixed id.

Steps to replicate:

* visit *Compute* > *Physical Infrastructure* > *Providers*,
* click on a provider that has multiple physical systems,
* expand the physical servers list by clicking on the servers icon or number,
* you should now be on the *Compute > Physical Infrastructure > Providers > Physical Infrastructure Providers > NAME_OF_PROVIDER > NAME_OF_PROVIDER (All Physical Servers)* or in the URL: `/ems_physical_infra/PROVIDER_ID?display=physical_servers#/`,
* select multiple servers (e.g., by clicking *Select All* at the bottom of the page),
* click *Lifecycle* > *Provision Selected Physical Servers*,
* notice the text: *Number of servers to be provisioned: 1*. Expected number should have matched the number of selected servers,
* fill in the form and click *Provision*,
* switch to *Services* > *Requests*,
* open the request that you have just created,
* expected result: *Affected Physical Servers* to contain the list of the servers selected. In reality, we get a "No Records Found."

Note that the request's API call, in my case, always contains:

```
results[0].options.src_ids = ["2"]
```

**Comment by matejart** [comment]
The issue applies to all the Lifecycle operations on this list.

**Comment by miha-plesko** [comment]
Should be fixed by https://github.com/ManageIQ/manageiq-providers-redfish/pull/80. I forgot there are three ways to access same thing; we had similar issue with cloud volumes page some time ago @martinpovolny if you still remember :)
